#!/bin/bash

cd ${JARVIS_HOME}

start() {

    lockPID="./lock.pid"
    # Check IF PROGRAM IS RUNNING
    if [ -f ${lockPID} ]; then
        pid=`cat ${lockPID}`
        ps -ef | grep -v grep | grep " ${pid} " | grep "${0}" > /dev/null
        if [ $? -eq 0 ]; then
            # WE ARE RUNNING - WE FORCE STOP
            echo "Jarvis Server already running"
            exit 1
        fi
    fi

    mv ${JARVIS_LOG} ${JARVIS_OLD_LOG}

    echo "Starting mjpg_streamer - `date '+%d/%m/%Y %H:%M:%S'`"
    /usr/local/bin/mjpg_streamer -i "/usr/local/lib/input_uvc.so" -o "/usr/local/lib/output_http.so -w /usr/local/www -p 8090" >/dev/null 2> /dev/null &
    echo "mjpg_streamer Started - `date '+%d/%m/%Y %H:%M:%S'`"

    echo "Starting pigpiod - `date '+%d/%m/%Y %H:%M:%S'`"
    sudo service pigpiod start
    echo "pigpiod Started - `date '+%d/%m/%Y %H:%M:%S'`"

    echo "Starting gpsd - `date '+%d/%m/%Y %H:%M:%S'`"
    sudo gpsd /dev/ttyUSB0 -F /var/run/gpsd.sock
    sudo service gpsd start
    echo "gpsd Started - `date '+%d/%m/%Y %H:%M:%S'`"

    echo "Starting Jarvis Server - `date '+%d/%m/%Y %H:%M:%S'`"
    cd ${JARVIS_APP}
    python3 -u Jarvis.py &
    echo "Jarvis Server started."
}

stop() {
    pid=`ps -ef | grep 'Jarvis.py' | grep -v grep | awk '{ print $2 }'`
    echo ${pid}
    kill ${pid}
    sleep 2
    echo "Stopping Server - `date '+%d/%m/%Y %H:%M:%S'`"
    echo "Server killed."

    pid=`ps -ef | grep 'mjpg_streamer' | grep -v grep | awk '{ print $2 }'`
    echo ${pid}
    kill ${pid}
	echo "Stopping mjpg_streamer - `date '+%d/%m/%Y %H:%M:%S'`"
    echo "mjpg_streamer killed."

    sudo service pigpiod stop
	echo "Stopping pigpiod - `date '+%d/%m/%Y %H:%M:%S'`"
    echo "pigpiod killed."

    sudo service gpsd stop
    echo "Stopping gpsd - `date '+%d/%m/%Y %H:%M:%S'`"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: jarvisServer {start|stop|restart}"
    exit 1
esac
exit 0
